branches:
  only:
    - master
    - develop
    - /^release\/.*$/
    - /^feature\/.*$/

notifications:
  email: false

language: python

python:
  - "2.6"
  - "2.7"

install: make

script: make test
